using CSClay;
using SkiaSharp;
using CSClay.Renderers.SkiaSharp;
using Xunit;

namespace CSClay.Renderers.SkiaSharp.Tests;

public class RendererTests
{
    [Fact]
    public void TestRenderToPng()
    {
        const int width = 800;
        const int height = 600;

        var arena = new ClayArena(1024 * 1024 * 4);
        var context = new ClayContext(arena);
        UI.SetCurrentContext(context);

        // Simple text measurement
        context.TextMeasure = (text, config) => new Dimensions(text.Length * (config.FontSize * 0.6f), config.FontSize);

        UI.Begin(arena, new Dimensions(width, height));

        UI.Container("root", new LayoutConfig 
        { 
            LayoutDirection = LayoutDirection.TopToBottom,
            Padding = new Padding(20, 20),
            ChildGap = 10,
            Sizing = new Sizing { Width = SizingAxis.Fixed(width), Height = SizingAxis.Fixed(height) }
        }, new Color(40, 44, 52), () => 
        {
            UI.Container("header", new LayoutConfig 
            { 
                Sizing = new Sizing { Width = SizingAxis.Grow(), Height = SizingAxis.Fixed(60) },
                ChildAlignment = new ChildAlignment { X = LayoutAlignmentX.Center, Y = LayoutAlignmentY.Center }
            }, new Color(60, 64, 72), () => 
            {
                UI.Text("CSClay SkiaSharp Renderer", new TextConfig { FontSize = 32, TextColor = new Color(255, 255, 255) });
            });

            UI.Container("body", new LayoutConfig 
            { 
                LayoutDirection = LayoutDirection.LeftToRight,
                ChildGap = 20,
                Sizing = new Sizing { Width = SizingAxis.Grow(), Height = SizingAxis.Grow() }
            }, () => 
            {
                UI.Container("sidebar", new LayoutConfig 
                { 
                    Sizing = new Sizing { Width = SizingAxis.Fixed(200), Height = SizingAxis.Grow() },
                    Padding = new Padding(10, 10),
                    ChildGap = 10
                }, new Color(50, 54, 62), () => 
                {
                    for (int i = 1; i <= 3; i++)
                    {
                        UI.Container($"item-{i}", new LayoutConfig 
                        { 
                            Sizing = new Sizing { Width = SizingAxis.Grow(), Height = SizingAxis.Fixed(40) },
                            ChildAlignment = new ChildAlignment { X = LayoutAlignmentX.Center, Y = LayoutAlignmentY.Center }
                        }, new Color(70, 74, 82), () => 
                        {
                            UI.Text($"Menu {i}", new TextConfig { FontSize = 18, TextColor = new Color(255, 255, 255) });
                        });
                    }
                });

                UI.Container("content", new LayoutConfig 
                { 
                    Sizing = new Sizing { Width = SizingAxis.Grow(), Height = SizingAxis.Grow() },
                    Padding = new Padding(20, 20),
                    ChildGap = 20
                }, new Color(30, 34, 42), () => 
                {
                    UI.Text("Renderer Output Test", new TextConfig { FontSize = 24, TextColor = new Color(255, 255, 255) });
                    
                    UI.Text("This image was generated by the csclay layout engine and rendered via SkiaSharp.", 
                        new TextConfig { FontSize = 18, TextColor = new Color(200, 200, 200), WrapMode = TextWrapMode.Words });

                    UI.Container("row", new LayoutConfig { LayoutDirection = LayoutDirection.LeftToRight, ChildGap = 10 }, () => 
                    {
                        UI.Container("box1", new LayoutConfig { Sizing = new Sizing { Width = SizingAxis.Fixed(50), Height = SizingAxis.Fixed(50) } }, new Color(255, 100, 100));
                        UI.Container("box2", new LayoutConfig { Sizing = new Sizing { Width = SizingAxis.Fixed(50), Height = SizingAxis.Fixed(50) } }, new Color(100, 255, 100));
                        UI.Container("box3", new LayoutConfig { Sizing = new Sizing { Width = SizingAxis.Fixed(50), Height = SizingAxis.Fixed(50) } }, new Color(100, 100, 255));
                    });
                });
            });
        });

        var commands = UI.End();

        // Render to bitmap
        using var surface = SKSurface.Create(new SKImageInfo(width, height));
        var canvas = surface.Canvas;
        canvas.Clear(SKColors.Black);

        SkiaSharpRenderer.Render(canvas, commands, context);

        // Save to PNG
        using var image = surface.Snapshot();
        using var data = image.Encode(SKEncodedImageFormat.Png, 100);
        
        var artifactsDir = Path.Combine(Directory.GetCurrentDirectory(), "TestOutput");
        if (!Directory.Exists(artifactsDir)) Directory.CreateDirectory(artifactsDir);
        
        var filePath = Path.Combine(artifactsDir, "layout_output.png");
        using var stream = File.OpenWrite(filePath);
        data.SaveTo(stream);

        Assert.True(File.Exists(filePath));
    }
}
